-- Generated by scripts/generate-seed.mjs from src/content/demo-content.json.
-- Do not edit by hand. Safe to run more than once.
-- Timezone used for event times: Asia/Kolkata

insert into public.team_members (id, name, designation, photo_url, bio, linkedin_url, github_url, twitter_url, instagram_url, email, tenure, sort_order) values
  ('a0000000-0000-4000-8000-000000000001', 'Aarav Mehta', 'President', null, 'Final-year CSE. Breaks web apps for fun, writes the fixes for work. Leads club strategy and partnerships.', 'https://www.linkedin.com/', 'https://github.com/', null, 'https://www.instagram.com/', null, '2026–27', 1),
  ('a0000000-0000-4000-8000-000000000002', 'Diya Sharma', 'Vice President', null, 'Cloud security enthusiast and AWS community builder. Keeps every event on schedule.', 'https://www.linkedin.com/', 'https://github.com/', 'https://x.com/', null, null, '2026–27', 2),
  ('a0000000-0000-4000-8000-000000000003', 'Rohan Iyer', 'Technical Lead', null, 'Full-stack developer and maintainer of the club''s open-source projects, including this website.', 'https://www.linkedin.com/', 'https://github.com/', null, null, null, '2026–27', 3),
  ('a0000000-0000-4000-8000-000000000004', 'Kabir Singh', 'CTF & Research Lead', null, 'Reverse engineer and pwn player. Designs the challenges for ISSA CTF every year.', 'https://www.linkedin.com/', 'https://github.com/', null, null, null, '2026–27', 4),
  ('a0000000-0000-4000-8000-000000000005', 'Sneha Kulkarni', 'Events & Outreach Head', null, 'Runs workshops, speaker sessions and the campus cyber-awareness drive.', 'https://www.linkedin.com/', null, null, 'https://www.instagram.com/', null, '2026–27', 5),
  ('a0000000-0000-4000-8000-000000000006', 'Ananya Rao', 'Design & Media Lead', null, 'UI/UX designer behind the ISSA brand. Photographs every event you see in the gallery.', 'https://www.linkedin.com/', null, null, 'https://www.instagram.com/', null, '2026–27', 6),
  ('a0000000-0000-4000-8000-000000000007', 'Vikram Nair', 'AI Security Lead', null, 'Researches adversarial ML and LLM red-teaming. Mentors the PhishNet project.', 'https://www.linkedin.com/', 'https://github.com/', null, null, null, '2026–27', 7),
  ('a0000000-0000-4000-8000-000000000008', 'Meera Joshi', 'Treasurer & Operations', null, 'Manages budgets, sponsorships and logistics so the tech team can focus on building.', 'https://www.linkedin.com/', null, null, null, null, '2026–27', 8)
on conflict (id) do nothing;

insert into public.projects (id, title, summary, description, tags, status, repo_url, demo_url, cover_url, contributors, is_featured, sort_order) values
  ('b0000000-0000-4000-8000-000000000001', 'PhishNet', 'Browser extension that flags phishing pages in real time using a lightweight on-device ML model.', 'PhishNet extracts 40+ URL and DOM features and scores pages with a quantised gradient-boosted model that runs entirely in the browser, so no browsing data leaves the device.', array['AI/ML', 'Security', 'Browser']::text[], 'ongoing', 'https://github.com/', null, null, array['Vikram Nair', 'Aarav Mehta']::text[], true, 1),
  ('b0000000-0000-4000-8000-000000000002', 'ISSA CTF Platform', 'Self-hosted capture-the-flag platform with dynamic scoring, team play and 60+ original challenges.', 'Containerised challenge infrastructure with per-team instances, automated flag rotation and a live scoreboard. Powers ISSA CTF every year.', array['Security', 'DevOps', 'CTF']::text[], 'completed', 'https://github.com/', null, null, array['Kabir Singh', 'Rohan Iyer']::text[], true, 2),
  ('b0000000-0000-4000-8000-000000000003', 'Honeypot Lab', 'A network of low-interaction honeypots that logs real-world attacker behaviour for research.', 'SSH, HTTP and SMB honeypots feed an ELK pipeline. Monthly reports summarise attack sources, credentials tried and malware samples collected.', array['Security', 'Networking', 'Data']::text[], 'ongoing', 'https://github.com/', null, null, array['Kabir Singh']::text[], false, 3),
  ('b0000000-0000-4000-8000-000000000004', 'ISSA Web Platform', 'This website: events, ticketing, live quizzes, submissions and an AI assistant, built on Next.js and Supabase.', 'Role-based access control enforced in Postgres, realtime quiz hosting and CSV/JSON exports for the core team.', array['Web', 'Open Source']::text[], 'ongoing', 'https://github.com/', '/', null, array['Rohan Iyer', 'Ananya Rao']::text[], true, 4),
  ('b0000000-0000-4000-8000-000000000005', 'LogLens', 'SIEM-lite dashboard that parses auth logs and alerts on brute-force and impossible-travel logins.', 'Streams syslog into DuckDB, runs detection rules written in SQL and pushes alerts to Discord.', array['Security', 'Data', 'Web']::text[], 'completed', 'https://github.com/', null, null, array['Diya Sharma', 'Meera Joshi']::text[], false, 5),
  ('b0000000-0000-4000-8000-000000000006', 'SecureVault', 'Educational zero-knowledge password manager demonstrating client-side encryption done right.', 'Argon2id key derivation, AES-GCM vault encryption and a threat model document written for first-year students.', array['Cryptography', 'Web']::text[], 'completed', 'https://github.com/', null, null, array['Aarav Mehta']::text[], false, 6),
  ('b0000000-0000-4000-8000-000000000007', 'DeepCheck', 'Research prototype that detects AI-generated profile photos in campus social platforms.', 'Fine-tuned vision transformer with frequency-domain features. Evaluated on a dataset collected with consent at ISSA events.', array['AI/ML', 'Research']::text[], 'ongoing', 'https://github.com/', null, null, array['Vikram Nair', 'Ananya Rao']::text[], false, 7)
on conflict (id) do nothing;

insert into public.achievements (id, title, recipients, category, position, description, achieved_on, link_url, image_url, is_featured) values
  ('c0000000-0000-4000-8000-000000000001', 'National Hackathon — Grand Finale Winners', 'Team Null Pointers · Rohan Iyer, Meera Joshi, Diya Sharma', 'hackathon', 'Winner', 'Built a privacy-preserving attendance system using on-device face matching in 36 hours.', (current_date - 160), null, null, true),
  ('c0000000-0000-4000-8000-000000000002', 'Inter-college CTF Championship', 'Team 0xISSA · Kabir Singh, Aarav Mehta, Vikram Nair', 'ctf', '1st Place', 'Solved 31 of 34 challenges across web, pwn, crypto and forensics.', (current_date - 95), null, null, true),
  ('c0000000-0000-4000-8000-000000000003', 'Security+ Study Group', '12 ISSA members', 'certification', 'Certified', 'Members cleared CompTIA Security+ after the club''s 10-week study programme.', (current_date - 60), null, null, false),
  ('c0000000-0000-4000-8000-000000000004', 'Best Paper Award — Student Research Symposium', 'Vikram Nair, Ananya Rao', 'publication', 'Best Paper', '“Detecting synthetic profile images with frequency-domain cues” (DeepCheck).', (current_date - 40), null, null, true),
  ('c0000000-0000-4000-8000-000000000005', 'Open-source Summer Programme', 'Rohan Iyer', 'award', 'Contributor', 'Selected to contribute to a major web security scanner over the summer.', (current_date - 120), null, null, false),
  ('c0000000-0000-4000-8000-000000000006', 'University Cyber Challenge', 'Team Stack Smashers · Kabir Singh, Sneha Kulkarni', 'ctf', 'Top 50', 'Placed in the global top 50 among 900+ university teams.', (current_date - 210), null, null, false)
on conflict (id) do nothing;

insert into public.events (id, slug, title, summary, description, category, location, mode, starts_at, ends_at, capacity, registration_open, members_only, submissions_open, submission_deadline, submission_guidelines, tags, is_featured, is_published) values
  ('e0000000-0000-4000-8000-000000000001', 'hack-night-web-exploitation-101', 'Hack Night: Web Exploitation 101', 'Hands-on intro to the OWASP Top 10. Break a deliberately vulnerable app, then patch it.', 'Bring your laptop — we''ll hack a deliberately vulnerable web app together.

**You''ll learn**
- How SQL injection, XSS and CSRF actually work
- Using Burp Suite to intercept and modify requests
- Writing the fix, not just the exploit

**Prerequisites:** a laptop with a modern browser. We''ll share a lab VM on the day.

All hacking happens only on lab targets we own. Attacking systems without permission is illegal and against the ISSA code of conduct.', 'workshop', 'Lab 3, CSE Block', 'offline', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '5 days' + time '17:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '5 days' + time '17:00') at time zone 'Asia/Kolkata') + interval '3 hours'), 60, true, false, false, null, null, array['web', 'owasp', 'beginner-friendly']::text[], true, true),
  ('e0000000-0000-4000-8000-000000000002', 'cyber-quiz-night', 'Cyber Quiz Night', 'A live, Kahoot-style quiz on security, networks and tech trivia. Fastest correct answers win.', 'Play live from your phone while questions appear on the big screen.

- 8 questions, 20 seconds each
- Faster correct answers earn more points (up to 1,000 per question)
- Top 3 win swag and a podium badge on their ISSA profile

Sign in before the quiz starts so you can join the lobby instantly.', 'competition', 'Seminar Hall 2', 'hybrid', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '8 days' + time '18:30') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '8 days' + time '18:30') at time zone 'Asia/Kolkata') + interval '1.5 hours'), 120, true, false, false, null, null, array['quiz', 'fun']::text[], true, true),
  ('e0000000-0000-4000-8000-000000000003', 'buildsec-hackathon', 'BuildSec Hackathon 2026', '36 hours to build secure-by-design software for campus problems. Teams of up to four.', 'Tracks: **Campus Safety**, **Privacy Tech** and **Open Innovation**.

- Teams of 1–4; register individually and enter the same team name
- Submit your repository, a short demo video link and a pitch deck before the deadline
- Judging: impact (30%), security (30%), technical depth (25%), presentation (15%)

Mentors from the core team will be around all night. Food is on us.', 'hackathon', 'Innovation Centre', 'offline', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '20 days' + time '09:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '20 days' + time '09:00') at time zone 'Asia/Kolkata') + interval '36 hours'), 150, true, false, true, (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '20 days' + time '09:00') at time zone 'Asia/Kolkata') + interval '36 hours'), 'Submit once per team (from any one member''s account) with your team name. Include a public repository link and optionally a demo link. You may upload a single .zip, .pdf or .pptx up to 10 MB (link larger files from Drive or GitHub). You can update your submission until the deadline.', array['hackathon', 'teams', 'prizes']::text[], true, true),
  ('e0000000-0000-4000-8000-000000000004', 'issa-ctf-2026', 'ISSA CTF 2026', 'Our flagship 24-hour jeopardy-style capture-the-flag. Web, pwn, crypto, forensics and OSINT.', 'Compete solo or in teams of up to three. Challenges range from beginner to brutal.

**Members only** — sign up with your college email to be auto-verified as a member.

Flag format: `issa{...}`. Sharing flags between teams leads to disqualification.', 'ctf', 'Online + CSE Block Labs', 'hybrid', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '34 days' + time '10:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '34 days' + time '10:00') at time zone 'Asia/Kolkata') + interval '24 hours'), 300, true, true, false, null, null, array['ctf', 'competition']::text[], false, true),
  ('e0000000-0000-4000-8000-000000000005', 'orientation-2026', 'Orientation 2026: Welcome to ISSA', 'Meet the core team, see what we build, and find your track: security, dev, AI or design.', 'Our kick-off session for new members with live demos, a mini CTF and pizza.', 'meetup', 'Main Auditorium', 'offline', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-21 days' + time '16:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-21 days' + time '16:00') at time zone 'Asia/Kolkata') + interval '2 hours'), null, false, false, false, null, null, array['community']::text[], false, true),
  ('e0000000-0000-4000-8000-000000000006', 'guest-talk-zero-trust', 'Guest Talk: Zero Trust in Practice', 'An industry security architect on moving from perimeter security to zero trust.', 'Covered identity-aware proxies, device posture and micro-segmentation, with a Q&A on security careers.', 'talk', 'Seminar Hall 1', 'hybrid', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-48 days' + time '15:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-48 days' + time '15:00') at time zone 'Asia/Kolkata') + interval '1.5 hours'), 200, false, false, false, null, null, array['talk', 'careers']::text[], false, true),
  ('e0000000-0000-4000-8000-000000000007', 'linux-networking-bootcamp', 'Linux & Networking Bootcamp', 'Two-day bootcamp covering the shell, permissions, TCP/IP, Wireshark and firewall basics.', 'The foundation for everything else we do. Slides and lab sheets are shared with attendees.', 'workshop', 'Lab 1, CSE Block', 'offline', ((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-75 days' + time '10:00') at time zone 'Asia/Kolkata'), (((date_trunc('day', now() at time zone 'Asia/Kolkata') + interval '-75 days' + time '10:00') at time zone 'Asia/Kolkata') + interval '6 hours'), 80, false, false, false, null, null, array['linux', 'networking', 'beginner-friendly']::text[], false, true)
on conflict (id) do nothing;

insert into public.gallery_items (id, title, media_type, url, thumbnail_url, caption, event_id, taken_on, sort_order) values
  ('d0000000-0000-4000-8000-000000000001', 'Orientation 2026', 'image', null, null, 'A full auditorium for our 2026 kick-off.', 'e0000000-0000-4000-8000-000000000005', (current_date - 21), 1),
  ('d0000000-0000-4000-8000-000000000002', 'Hack Night crowd', 'image', null, null, 'Forty laptops, one vulnerable web app.', null, (current_date - 30), 2),
  ('d0000000-0000-4000-8000-000000000003', 'Watch: Cyber Security in 7 Minutes', 'video', 'https://www.youtube.com/watch?v=inWWhr5tnEA', null, 'The primer we screened at orientation (video by Simplilearn).', 'e0000000-0000-4000-8000-000000000005', (current_date - 21), 3),
  ('d0000000-0000-4000-8000-000000000004', 'Zero Trust Q&A', 'image', null, null, 'Career Q&A after the zero trust talk.', 'e0000000-0000-4000-8000-000000000006', (current_date - 48), 4),
  ('d0000000-0000-4000-8000-000000000005', 'Bootcamp labs', 'image', null, null, 'Packet captures and firewall rules on day two.', 'e0000000-0000-4000-8000-000000000007', (current_date - 74), 5),
  ('d0000000-0000-4000-8000-000000000006', 'CTF finals scoreboard', 'image', null, null, 'The final hour of the inter-college CTF.', null, (current_date - 95), 6),
  ('d0000000-0000-4000-8000-000000000007', 'Hackathon winners', 'image', null, null, 'Team Null Pointers with the grand finale trophy.', null, (current_date - 160), 7),
  ('d0000000-0000-4000-8000-000000000008', 'Cyber awareness drive', 'image', null, null, 'Teaching phishing spotting to 500+ students.', null, (current_date - 110), 8),
  ('d0000000-0000-4000-8000-000000000009', 'Core team 2026–27', 'image', null, null, 'The people behind ISSA this year.', null, (current_date - 25), 9)
on conflict (id) do nothing;

insert into public.quizzes (id, title, description, event_id, mode, status, opens_at, closes_at, members_only) values
  ('f0000000-0000-4000-8000-000000000001', 'Cyber Quiz Night — Live', 'Hosted live at Cyber Quiz Night. Join the lobby and wait for the host to start.', 'e0000000-0000-4000-8000-000000000002', 'live', 'published', null, null, false),
  ('f0000000-0000-4000-8000-000000000002', 'Security Fundamentals — Practice', 'A self-paced warm-up. Play any time this month; you''ll see whether each answer was right straight away.', null, 'self_paced', 'published', (now() + interval '-1 days'), (now() + interval '30 days'), false)
on conflict (id) do nothing;

insert into public.learning_resources (id, title, description, url, track, kind, level, is_free, source, tags, sort_order, is_featured) values
  ('a1000000-0000-4000-8000-000000000001', 'Cyber Security Roadmap', 'A visual, step-by-step map of what to learn first and what comes next.', 'https://roadmap.sh/cyber-security', 'Getting Started', 'roadmap', 'beginner', true, 'roadmap.sh', array['roadmap', 'career']::text[], 1, true),
  ('a1000000-0000-4000-8000-000000000002', 'CS50''s Introduction to Cybersecurity', 'Harvard''s free course on securing accounts, data, systems and software — no prerequisites.', 'https://cs50.harvard.edu/cybersecurity/', 'Getting Started', 'course', 'beginner', true, 'Harvard CS50', array['fundamentals']::text[], 2, true),
  ('a1000000-0000-4000-8000-000000000003', 'Linux Journey', 'Learn the Linux command line, permissions, processes and networking basics.', 'https://linuxjourney.com/', 'Linux & Networking', 'course', 'beginner', true, 'Linux Journey', array['linux', 'shell']::text[], 3, false),
  ('a1000000-0000-4000-8000-000000000004', 'OverTheWire: Bandit', 'A wargame that teaches the shell through 30+ small puzzles. The classic first CTF.', 'https://overthewire.org/wargames/bandit/', 'Linux & Networking', 'platform', 'beginner', true, 'OverTheWire', array['ctf', 'linux']::text[], 4, true),
  ('a1000000-0000-4000-8000-000000000005', 'Web Security Academy', 'Free interactive labs covering SQL injection, XSS, CSRF, SSRF and much more.', 'https://portswigger.net/web-security', 'Web Security', 'platform', 'intermediate', true, 'PortSwigger', array['web', 'labs', 'burp']::text[], 5, true),
  ('a1000000-0000-4000-8000-000000000006', 'OWASP Top 10', 'The industry reference for the most critical web application security risks.', 'https://owasp.org/www-project-top-ten/', 'Web Security', 'article', 'beginner', true, 'OWASP', array['web', 'owasp']::text[], 6, false),
  ('a1000000-0000-4000-8000-000000000007', 'MDN Web Docs', 'The best reference for HTML, CSS, JavaScript and how the web actually works.', 'https://developer.mozilla.org/', 'Web Development', 'notes', 'beginner', true, 'Mozilla', array['web', 'javascript']::text[], 7, false),
  ('a1000000-0000-4000-8000-000000000008', 'freeCodeCamp', 'Project-based certifications in web development, Python and more.', 'https://www.freecodecamp.org/', 'Web Development', 'course', 'beginner', true, 'freeCodeCamp', array['web', 'python']::text[], 8, false),
  ('a1000000-0000-4000-8000-000000000009', 'picoCTF', 'Beginner-friendly capture-the-flag practice with hints, run by Carnegie Mellon.', 'https://picoctf.org/', 'CTF Practice', 'platform', 'beginner', true, 'Carnegie Mellon University', array['ctf']::text[], 9, false),
  ('a1000000-0000-4000-8000-000000000010', 'TryHackMe', 'Guided, browser-based hacking rooms from complete beginner to advanced.', 'https://tryhackme.com/', 'CTF Practice', 'platform', 'beginner', false, 'TryHackMe', array['ctf', 'labs']::text[], 10, false),
  ('a1000000-0000-4000-8000-000000000011', 'Hack The Box Academy', 'Structured modules on penetration testing, from fundamentals to advanced.', 'https://academy.hackthebox.com/', 'CTF Practice', 'platform', 'intermediate', false, 'Hack The Box', array['pentest', 'labs']::text[], 11, false),
  ('a1000000-0000-4000-8000-000000000012', 'CyberChef', 'The "cyber Swiss army knife" for encoding, decoding, hashing and data analysis.', 'https://gchq.github.io/CyberChef/', 'Tools', 'tool', 'beginner', true, 'GCHQ', array['crypto', 'forensics']::text[], 12, false)
on conflict (id) do nothing;

insert into public.quiz_questions (id, quiz_id, position, prompt, options, time_limit, points, explanation) values
  ('00010001-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 0, 'Which TCP port does HTTPS use by default?', array['80', '443', '8080', '22']::text[], 20, 1000, 'HTTPS is HTTP over TLS, served on TCP port 443 by default.'),
  ('00010002-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 1, 'Which attack tricks a logged-in user''s browser into sending an unwanted request to a trusted site?', array['XSS', 'CSRF', 'SSRF', 'Clickjacking']::text[], 20, 1000, 'Cross-Site Request Forgery rides on the victim''s existing session. Anti-CSRF tokens and SameSite cookies defend against it.'),
  ('00010003-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 2, 'Which of these is a hash function rather than an encryption algorithm?', array['AES', 'RSA', 'SHA-256', 'ChaCha20']::text[], 20, 1000, 'SHA-256 is a one-way hash. AES and ChaCha20 are symmetric ciphers; RSA is asymmetric.'),
  ('00010004-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 3, 'In the CIA triad, what does the “I” stand for?', array['Identity', 'Integrity', 'Isolation', 'Inspection']::text[], 15, 1000, 'Confidentiality, Integrity, Availability.'),
  ('00010005-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 4, 'Which tool is best known for network port scanning?', array['Wireshark', 'Nmap', 'Burp Suite', 'John the Ripper']::text[], 15, 1000, 'Nmap discovers hosts and services. Wireshark captures packets, Burp proxies web traffic, John cracks passwords.'),
  ('00010006-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 5, 'What does adding a unique salt to each password hash defend against?', array['Network sniffing', 'Precomputed rainbow-table attacks', 'Phishing', 'Keyloggers']::text[], 20, 1000, 'Salts make precomputed tables useless and ensure identical passwords hash differently.'),
  ('00010007-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 6, 'Which HTTP response header restricts where scripts can load from, helping mitigate XSS?', array['Content-Security-Policy', 'X-Powered-By', 'Accept-Encoding', 'ETag']::text[], 20, 1000, 'A strict Content-Security-Policy blocks inline and untrusted scripts.'),
  ('00010008-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000001', 7, 'Which Linux command changes a file''s permission bits?', array['chown', 'chmod', 'chgrp', 'umask']::text[], 15, 1000, 'chmod changes mode bits; chown changes ownership.'),
  ('00020001-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 0, 'Phishing emails most commonly try to…', array['Steal credentials or deliver malware', 'Speed up your inbox', 'Update your operating system', 'Encrypt your files for safekeeping']::text[], 20, 1000, 'Phishing lures you into revealing credentials or running malware.'),
  ('00020002-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 1, 'Which of these passwords is strongest?', array['P@ssw0rd', 'correct-horse-battery-staple-42', '12345678', 'qwerty!']::text[], 20, 1000, 'Length beats complexity: a long passphrase has far more entropy than a short “complex” password.'),
  ('00020003-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 2, 'What does multi-factor authentication add to a login?', array['A second factor such as an OTP or security key', 'A longer password', 'A CAPTCHA', 'A VPN connection']::text[], 20, 1000, 'MFA requires something you have or are in addition to something you know.'),
  ('00020004-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 3, 'Which protocol should replace Telnet for remote administration?', array['FTP', 'SSH', 'SNMP', 'HTTP']::text[], 15, 1000, 'SSH encrypts the session; Telnet sends everything, including passwords, in plaintext.'),
  ('00020005-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 4, 'A “zero-day” vulnerability is…', array['A bug fixed on the day it was found', 'A flaw with no patch available because the vendor has had zero days to fix it', 'A virus that deletes itself after a day', 'An expired TLS certificate']::text[], 20, 1000, 'Zero-days are exploited before a fix exists.'),
  ('00020006-0000-4000-8000-000000000000', 'f0000000-0000-4000-8000-000000000002', 5, 'What is the primary job of a firewall?', array['Filter network traffic based on rules', 'Speed up internet access', 'Store passwords securely', 'Scan email attachments']::text[], 15, 1000, 'Firewalls allow or block traffic according to a rule set.')
on conflict (id) do nothing;

insert into public.quiz_answer_keys (question_id, correct_index) values
  ('00010001-0000-4000-8000-000000000000', 1),
  ('00010002-0000-4000-8000-000000000000', 1),
  ('00010003-0000-4000-8000-000000000000', 2),
  ('00010004-0000-4000-8000-000000000000', 1),
  ('00010005-0000-4000-8000-000000000000', 1),
  ('00010006-0000-4000-8000-000000000000', 1),
  ('00010007-0000-4000-8000-000000000000', 0),
  ('00010008-0000-4000-8000-000000000000', 1),
  ('00020001-0000-4000-8000-000000000000', 0),
  ('00020002-0000-4000-8000-000000000000', 1),
  ('00020003-0000-4000-8000-000000000000', 0),
  ('00020004-0000-4000-8000-000000000000', 1),
  ('00020005-0000-4000-8000-000000000000', 1),
  ('00020006-0000-4000-8000-000000000000', 0)
on conflict (question_id) do nothing;
