#!/usr/bin/env node
// Generates supabase/seed.sql from src/content/demo-content.json so the
// database seed and the offline demo content never drift apart.
//
//   node scripts/generate-seed.mjs            (timezone defaults to Asia/Kolkata)
//   CLUB_TIMEZONE=Europe/London node scripts/generate-seed.mjs
//
// Dates in the JSON are relative ("starts_in_days": 5) and are resolved with
// now() when the seed runs, so demo events always look current.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const content = JSON.parse(readFileSync(resolve(root, "src/content/demo-content.json"), "utf8"));
const tz = process.env.CLUB_TIMEZONE || process.env.NEXT_PUBLIC_CLUB_TIMEZONE || "Asia/Kolkata";

const lit = (value) => {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
};
const textArray = (values = []) => (values.length ? `array[${values.map(lit).join(", ")}]::text[]` : "'{}'::text[]");
const localTime = (days, time) =>
  `((date_trunc('day', now() at time zone ${lit(tz)}) + interval '${days} days' + time ${lit(time)}) at time zone ${lit(tz)})`;
const daysAgo = (days) => (days === null || days === undefined ? "null" : `(current_date - ${Number(days)})`);

const insert = (table, rows, conflict = "(id)") => {
  if (!rows.length) return "";
  const columns = Object.keys(rows[0]);
  const values = rows.map((row) => `  (${columns.map((c) => row[c]).join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values}\non conflict ${conflict} do nothing;\n`;
};

const out = [];
out.push(`-- Generated by scripts/generate-seed.mjs from src/content/demo-content.json.
-- Do not edit by hand. Safe to run more than once.
-- Timezone used for event times: ${tz}
`);

out.push(
  insert(
    "team_members",
    content.team.map((m) => ({
      id: lit(m.id),
      name: lit(m.name),
      designation: lit(m.designation),
      photo_url: lit(m.photo_url ?? null),
      bio: lit(m.bio ?? null),
      linkedin_url: lit(m.linkedin_url ?? null),
      github_url: lit(m.github_url ?? null),
      twitter_url: lit(m.twitter_url ?? null),
      instagram_url: lit(m.instagram_url ?? null),
      email: lit(m.email ?? null),
      tenure: lit(m.tenure ?? null),
      sort_order: lit(m.sort_order ?? 0),
    })),
  ),
);

out.push(
  insert(
    "projects",
    content.projects.map((p) => ({
      id: lit(p.id),
      title: lit(p.title),
      summary: lit(p.summary),
      description: lit(p.description ?? null),
      tags: textArray(p.tags),
      status: lit(p.status),
      repo_url: lit(p.repo_url ?? null),
      demo_url: lit(p.demo_url ?? null),
      cover_url: lit(p.cover_url ?? null),
      contributors: textArray(p.contributors),
      is_featured: lit(Boolean(p.is_featured)),
      sort_order: lit(p.sort_order ?? 0),
    })),
  ),
);

out.push(
  insert(
    "achievements",
    content.achievements.map((a) => ({
      id: lit(a.id),
      title: lit(a.title),
      recipients: lit(a.recipients),
      category: lit(a.category),
      position: lit(a.position ?? null),
      description: lit(a.description ?? null),
      achieved_on: daysAgo(a.achieved_days_ago),
      link_url: lit(a.link_url ?? null),
      image_url: lit(a.image_url ?? null),
      is_featured: lit(Boolean(a.is_featured)),
    })),
  ),
);

out.push(
  insert(
    "events",
    content.events.map((e) => {
      const start = localTime(e.starts_in_days, e.start_time);
      return {
        id: lit(e.id),
        slug: lit(e.slug),
        title: lit(e.title),
        summary: lit(e.summary),
        description: lit(e.description ?? null),
        category: lit(e.category),
        location: lit(e.location ?? null),
        mode: lit(e.mode),
        starts_at: start,
        ends_at: e.duration_hours ? `(${start} + interval '${e.duration_hours} hours')` : "null",
        capacity: lit(e.capacity ?? null),
        registration_open: lit(Boolean(e.registration_open)),
        members_only: lit(Boolean(e.members_only)),
        submissions_open: lit(Boolean(e.submissions_open)),
        submission_deadline:
          e.submission_deadline_hours_after_start != null
            ? `(${start} + interval '${e.submission_deadline_hours_after_start} hours')`
            : "null",
        submission_guidelines: lit(e.submission_guidelines ?? null),
        tags: textArray(e.tags),
        is_featured: lit(Boolean(e.is_featured)),
        is_published: "true",
      };
    }),
  ),
);

out.push(
  insert(
    "gallery_items",
    content.gallery.map((g) => ({
      id: lit(g.id),
      title: lit(g.title),
      media_type: lit(g.media_type),
      url: lit(g.url ?? null),
      thumbnail_url: lit(g.thumbnail_url ?? null),
      caption: lit(g.caption ?? null),
      event_id: lit(g.event_id ?? null),
      taken_on: daysAgo(g.taken_days_ago),
      sort_order: lit(g.sort_order ?? 0),
    })),
  ),
);

out.push(
  insert(
    "quizzes",
    content.quizzes.map((q) => ({
      id: lit(q.id),
      title: lit(q.title),
      description: lit(q.description ?? null),
      event_id: lit(q.event_id ?? null),
      mode: lit(q.mode),
      status: lit(q.status ?? "draft"),
      opens_at: q.opens_in_days != null ? `(now() + interval '${q.opens_in_days} days')` : "null",
      closes_at: q.closes_in_days != null ? `(now() + interval '${q.closes_in_days} days')` : "null",
      members_only: lit(Boolean(q.members_only)),
    })),
  ),
);

out.push(
  insert(
    "learning_resources",
    (content.learning ?? []).map((l) => ({
      id: lit(l.id),
      title: lit(l.title),
      description: lit(l.description),
      url: lit(l.url),
      track: lit(l.track),
      kind: lit(l.kind),
      level: lit(l.level),
      is_free: lit(Boolean(l.is_free)),
      source: lit(l.source ?? null),
      tags: textArray(l.tags),
      sort_order: lit(l.sort_order ?? 0),
      is_featured: lit(Boolean(l.is_featured)),
    })),
  ),
);

// Learning resources alone, for loading real starter content into production.
writeFileSync(
  resolve(root, "supabase/learning-starter.sql"),
  `-- Generated by scripts/generate-seed.mjs. Starter learning resources only (safe to run more than once).\n${out.at(-1)}`,
);

// Deterministic question ids keep the seed idempotent.
const questionId = (quizIndex, questionIndex) =>
  `${(quizIndex + 1).toString(16).padStart(4, "0")}${(questionIndex + 1).toString(16).padStart(4, "0")}-0000-4000-8000-000000000000`;

const questions = [];
const keys = [];
content.quizzes.forEach((quiz, qi) => {
  quiz.questions.forEach((q, i) => {
    const id = questionId(qi, i);
    questions.push({
      id: lit(id),
      quiz_id: lit(quiz.id),
      position: lit(i),
      prompt: lit(q.prompt),
      options: textArray(q.options),
      time_limit: lit(q.time_limit ?? 20),
      points: lit(q.points ?? 1000),
      explanation: lit(q.explanation ?? null),
    });
    keys.push({ question_id: lit(id), correct_index: lit(q.correct_index) });
  });
});
out.push(insert("quiz_questions", questions));
out.push(insert("quiz_answer_keys", keys, "(question_id)"));

writeFileSync(resolve(root, "supabase/seed.sql"), out.join("\n"));
console.log(`Wrote supabase/seed.sql (${questions.length} quiz questions, timezone ${tz})`);
